import Head from "next/head";

import About from "../components/index/about";
import Header from "../components/index/header";
import Slider from "../components/index/slider";
import Language from "../components/general/language";
import Link from "next/link";
import Best from "../components/index/best";
import Contact from "../components/index/contact";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <About />
      <Slider img="/restaurant-3.jpg">
        <h2>Menu</h2>
        <p>
          <Language textEn={"See all menu."} textEs={"Ver todo el menu."} />{" "}
          <Link href="/menu">
            <a>
              <Language textEn={"Here"} textEs={"Aquí"} />
            </a>
          </Link>
        </p>
      </Slider>
      <Best />
      <Slider img="/restaurant-4.jpg">
        <h2>
          <Language textEn={"Contact"} textEs={"Contacto"} />
        </h2>
      </Slider>
      <Contact />
      <Slider img="/restaurant-6.jpg">
        <h2>
          <Language textEn={"Visit us now!!!"} textEs={"Visitanos ahora!!!"} />
        </h2>
      </Slider>
      <style jsx>{`
        h2 {
          font-size: 2rem;
          margin-block-start: 0;
          margin-block-end: 0;
        }

        p {
          margin-block-start: 0;
          margin-block-end: 0;
        }

        p > a {
          font-size: 1.2rem;
        }
      `}</style>
    </>
  );
}
